LengthUnit = 0 # 0: kpc, 1: pc, 2: AU
ComovingUnits = 0 # 0: no, 1: yes
FlagCenter = 0 # 0: Highest density, 1: Fixed center, 2: Center of mass
#Center = [0, 0, 0]
FlagRotate = 0 # 0: w/r to velocity vector, 1: Fixed angle (requires Angle)
#Angle = 
Usage = 1
RadialBins = 100
RadMin = 0.01
ImgXBins = 1024
#ImgWidth = 20
ImgScreenRatio = 1
PSpaceBins = 1024
